#!/bin/bash
make
echo 1 1 1 yi2
./csim-ref -s 1 -E 1 -b 1 -t traces/yi2.trace
./csim -s 1 -E 1 -b 1 -t traces/yi2.trace
echo 4 2 4 yi
./csim-ref -s 4 -E 2 -b 4 -t traces/yi.trace
./csim -s 4 -E 2 -b 4 -t traces/yi.trace
echo 2 1 4 dave
./csim-ref -s 2 -E 1 -b 4 -t traces/dave.trace
./csim -s 2 -E 1 -b 4 -t traces/dave.trace
echo 2 1 3 trans
./csim-ref -s 2 -E 1 -b 3 -t traces/trans.trace
./csim -s 2 -E 1 -b 3 -t traces/trans.trace
echo 2 2 3 trans
./csim-ref -s 2 -E 2 -b 3 -t traces/trans.trace
./csim -s 2 -E 2 -b 3 -t traces/trans.trace
echo 2 4 3 trans
./csim-ref -s 2 -E 4 -b 3 -t traces/trans.trace
./csim -s 2 -E 4 -b 3 -t traces/trans.trace
echo 5 1 5 trans
./csim-ref -s 5 -E 1 -b 5 -t traces/trans.trace
./csim -s 5 -E 1 -b 5 -t traces/trans.trace
echo 5 1 5 long
./csim-ref -s 5 -E 1 -b 5 -t traces/long.trace
./csim -s 5 -E 1 -b 5 -t traces/long.trace
